name: locust
services:
- name: locust-web
  dockerfile_path: Dockerfile
  source_dir: /
  github:
    repo: tdutty/locust
    branch: main
    deploy_on_push: true
  instance_size_slug: basic-xs
  instance_count: 1
  http_port: 3002
  health_check:
    http_path: /
  envs:
  - key: NODE_ENV
    value: production
    scope: RUN_AND_BUILD_TIME
  - key: JWT_SECRET
    value: ${JWT_SECRET}
    type: SECRET
    scope: RUN_AND_BUILD_TIME
  - key: SMTP_HOST
    value: smtp.porkbun.com
    scope: RUN_AND_BUILD_TIME
  - key: SMTP_PORT
    value: "587"
    scope: RUN_AND_BUILD_TIME
  - key: SMTP_USER
    value: tgilbert@sweetlease.io
    scope: RUN_AND_BUILD_TIME
  - key: SMTP_PASSWORD
    value: ${SMTP_PASSWORD}
    type: SECRET
    scope: RUN_AND_BUILD_TIME
  - key: IMAP_HOST
    value: imap.porkbun.com
    scope: RUN_AND_BUILD_TIME
  - key: IMAP_PORT
    value: "993"
    scope: RUN_AND_BUILD_TIME
  - key: GRASSHOPPER_API_URL
    value: http://198.199.78.62:8080
    scope: RUN_AND_BUILD_TIME
  - key: CRICKET_API_URL
    value: http://198.199.78.62:8081
    scope: RUN_AND_BUILD_TIME
  - key: NEXT_PUBLIC_APP_URL
    value: ${APP_URL}
    scope: RUN_AND_BUILD_TIME
